import type { ReadingPlan } from "@/lib/user/types";

export const READING_PLANS: ReadingPlan[] = [
  {
    id: "getting-to-know-jesus",
    name: "Getting to Know Jesus",
    description: "Perfect for new believers - read John and Matthew to meet Jesus",
    duration: 49,
    readings: [
      // John 1-21 (21 days)
      { day: 1, passages: [{ bookId: "JHN", chapter: 1 }] },
      { day: 2, passages: [{ bookId: "JHN", chapter: 2 }] },
      { day: 3, passages: [{ bookId: "JHN", chapter: 3 }] },
      { day: 4, passages: [{ bookId: "JHN", chapter: 4 }] },
      { day: 5, passages: [{ bookId: "JHN", chapter: 5 }] },
      { day: 6, passages: [{ bookId: "JHN", chapter: 6 }] },
      { day: 7, passages: [{ bookId: "JHN", chapter: 7 }] },
      { day: 8, passages: [{ bookId: "JHN", chapter: 8 }] },
      { day: 9, passages: [{ bookId: "JHN", chapter: 9 }] },
      { day: 10, passages: [{ bookId: "JHN", chapter: 10 }] },
      { day: 11, passages: [{ bookId: "JHN", chapter: 11 }] },
      { day: 12, passages: [{ bookId: "JHN", chapter: 12 }] },
      { day: 13, passages: [{ bookId: "JHN", chapter: 13 }] },
      { day: 14, passages: [{ bookId: "JHN", chapter: 14 }] },
      { day: 15, passages: [{ bookId: "JHN", chapter: 15 }] },
      { day: 16, passages: [{ bookId: "JHN", chapter: 16 }] },
      { day: 17, passages: [{ bookId: "JHN", chapter: 17 }] },
      { day: 18, passages: [{ bookId: "JHN", chapter: 18 }] },
      { day: 19, passages: [{ bookId: "JHN", chapter: 19 }] },
      { day: 20, passages: [{ bookId: "JHN", chapter: 20 }] },
      { day: 21, passages: [{ bookId: "JHN", chapter: 21 }] },
      // Matthew 1-28 (28 days)
      { day: 22, passages: [{ bookId: "MAT", chapter: 1 }] },
      { day: 23, passages: [{ bookId: "MAT", chapter: 2 }] },
      { day: 24, passages: [{ bookId: "MAT", chapter: 3 }] },
      { day: 25, passages: [{ bookId: "MAT", chapter: 4 }] },
      { day: 26, passages: [{ bookId: "MAT", chapter: 5 }] },
      { day: 27, passages: [{ bookId: "MAT", chapter: 6 }] },
      { day: 28, passages: [{ bookId: "MAT", chapter: 7 }] },
      { day: 29, passages: [{ bookId: "MAT", chapter: 8 }] },
      { day: 30, passages: [{ bookId: "MAT", chapter: 9 }] },
      { day: 31, passages: [{ bookId: "MAT", chapter: 10 }] },
      { day: 32, passages: [{ bookId: "MAT", chapter: 11 }] },
      { day: 33, passages: [{ bookId: "MAT", chapter: 12 }] },
      { day: 34, passages: [{ bookId: "MAT", chapter: 13 }] },
      { day: 35, passages: [{ bookId: "MAT", chapter: 14 }] },
      { day: 36, passages: [{ bookId: "MAT", chapter: 15 }] },
      { day: 37, passages: [{ bookId: "MAT", chapter: 16 }] },
      { day: 38, passages: [{ bookId: "MAT", chapter: 17 }] },
      { day: 39, passages: [{ bookId: "MAT", chapter: 18 }] },
      { day: 40, passages: [{ bookId: "MAT", chapter: 19 }] },
      { day: 41, passages: [{ bookId: "MAT", chapter: 20 }] },
      { day: 42, passages: [{ bookId: "MAT", chapter: 21 }] },
      { day: 43, passages: [{ bookId: "MAT", chapter: 22 }] },
      { day: 44, passages: [{ bookId: "MAT", chapter: 23 }] },
      { day: 45, passages: [{ bookId: "MAT", chapter: 24 }] },
      { day: 46, passages: [{ bookId: "MAT", chapter: 25 }] },
      { day: 47, passages: [{ bookId: "MAT", chapter: 26 }] },
      { day: 48, passages: [{ bookId: "MAT", chapter: 27 }] },
      { day: 49, passages: [{ bookId: "MAT", chapter: 28 }] },
    ],
  },
  {
    id: "gospels-30",
    name: "The Gospels in 30 Days",
    description: "Read through all four Gospels to understand the life of Jesus",
    duration: 30,
    readings: [
      { day: 1, passages: [{ bookId: "MAT", chapter: 1 }, { bookId: "MAT", chapter: 2 }] },
      { day: 2, passages: [{ bookId: "MAT", chapter: 3 }, { bookId: "MAT", chapter: 4 }] },
      { day: 3, passages: [{ bookId: "MAT", chapter: 5 }, { bookId: "MAT", chapter: 6 }] },
      { day: 4, passages: [{ bookId: "MAT", chapter: 7 }, { bookId: "MAT", chapter: 8 }] },
      { day: 5, passages: [{ bookId: "MAT", chapter: 9 }, { bookId: "MAT", chapter: 10 }] },
      { day: 6, passages: [{ bookId: "MAT", chapter: 11 }, { bookId: "MAT", chapter: 12 }] },
      { day: 7, passages: [{ bookId: "MAT", chapter: 13 }, { bookId: "MAT", chapter: 14 }] },
      { day: 8, passages: [{ bookId: "MAT", chapter: 15 }, { bookId: "MAT", chapter: 16 }] },
      { day: 9, passages: [{ bookId: "MAT", chapter: 17 }, { bookId: "MAT", chapter: 18 }] },
      { day: 10, passages: [{ bookId: "MAT", chapter: 19 }, { bookId: "MAT", chapter: 20 }] },
      { day: 11, passages: [{ bookId: "MAT", chapter: 21 }, { bookId: "MAT", chapter: 22 }] },
      { day: 12, passages: [{ bookId: "MAT", chapter: 23 }, { bookId: "MAT", chapter: 24 }] },
      { day: 13, passages: [{ bookId: "MAT", chapter: 25 }, { bookId: "MAT", chapter: 26 }] },
      { day: 14, passages: [{ bookId: "MAT", chapter: 27 }, { bookId: "MAT", chapter: 28 }] },
      { day: 15, passages: [{ bookId: "MRK", chapter: 1 }, { bookId: "MRK", chapter: 2 }, { bookId: "MRK", chapter: 3 }] },
      { day: 16, passages: [{ bookId: "MRK", chapter: 4 }, { bookId: "MRK", chapter: 5 }, { bookId: "MRK", chapter: 6 }] },
      { day: 17, passages: [{ bookId: "MRK", chapter: 7 }, { bookId: "MRK", chapter: 8 }, { bookId: "MRK", chapter: 9 }] },
      { day: 18, passages: [{ bookId: "MRK", chapter: 10 }, { bookId: "MRK", chapter: 11 }, { bookId: "MRK", chapter: 12 }] },
      { day: 19, passages: [{ bookId: "MRK", chapter: 13 }, { bookId: "MRK", chapter: 14 }, { bookId: "MRK", chapter: 15 }, { bookId: "MRK", chapter: 16 }] },
      { day: 20, passages: [{ bookId: "LUK", chapter: 1 }, { bookId: "LUK", chapter: 2 }] },
      { day: 21, passages: [{ bookId: "LUK", chapter: 3 }, { bookId: "LUK", chapter: 4 }] },
      { day: 22, passages: [{ bookId: "LUK", chapter: 5 }, { bookId: "LUK", chapter: 6 }] },
      { day: 23, passages: [{ bookId: "LUK", chapter: 7 }, { bookId: "LUK", chapter: 8 }] },
      { day: 24, passages: [{ bookId: "LUK", chapter: 9 }, { bookId: "LUK", chapter: 10 }] },
      { day: 25, passages: [{ bookId: "LUK", chapter: 11 }, { bookId: "LUK", chapter: 12 }, { bookId: "LUK", chapter: 13 }] },
      { day: 26, passages: [{ bookId: "LUK", chapter: 14 }, { bookId: "LUK", chapter: 15 }, { bookId: "LUK", chapter: 16 }] },
      { day: 27, passages: [{ bookId: "LUK", chapter: 17 }, { bookId: "LUK", chapter: 18 }, { bookId: "LUK", chapter: 19 }] },
      { day: 28, passages: [{ bookId: "LUK", chapter: 20 }, { bookId: "LUK", chapter: 21 }, { bookId: "LUK", chapter: 22 }] },
      { day: 29, passages: [{ bookId: "LUK", chapter: 23 }, { bookId: "LUK", chapter: 24 }] },
      { day: 30, passages: [{ bookId: "JHN", chapter: 1 }, { bookId: "JHN", chapter: 2 }, { bookId: "JHN", chapter: 3 }] },
    ],
  },
  {
    id: "psalms-30",
    name: "Psalms in 30 Days",
    description: "Experience the full range of human emotion in worship and prayer",
    duration: 30,
    readings: Array.from({ length: 30 }, (_, i) => ({
      day: i + 1,
      passages: Array.from({ length: 5 }, (_, j) => ({
        bookId: "PSA",
        chapter: i * 5 + j + 1,
      })).filter((p) => p.chapter <= 150),
    })),
  },
  {
    id: "proverbs-31",
    name: "Proverbs in 31 Days",
    description: "Daily wisdom for practical living",
    duration: 31,
    readings: Array.from({ length: 31 }, (_, i) => ({
      day: i + 1,
      passages: [{ bookId: "PRO", chapter: i + 1 }],
    })),
  },
  {
    id: "new-believer",
    name: "New Believer's Journey",
    description: "Essential passages to understand the Christian faith",
    duration: 14,
    readings: [
      { day: 1, passages: [{ bookId: "JHN", chapter: 3 }] },
      { day: 2, passages: [{ bookId: "ROM", chapter: 8 }] },
      { day: 3, passages: [{ bookId: "PSA", chapter: 23 }] },
      { day: 4, passages: [{ bookId: "MAT", chapter: 5 }] },
      { day: 5, passages: [{ bookId: "MAT", chapter: 6 }] },
      { day: 6, passages: [{ bookId: "MAT", chapter: 7 }] },
      { day: 7, passages: [{ bookId: "1CO", chapter: 13 }] },
      { day: 8, passages: [{ bookId: "ROM", chapter: 12 }] },
      { day: 9, passages: [{ bookId: "EPH", chapter: 6 }] },
      { day: 10, passages: [{ bookId: "PHP", chapter: 4 }] },
      { day: 11, passages: [{ bookId: "JAS", chapter: 1 }] },
      { day: 12, passages: [{ bookId: "1JN", chapter: 4 }] },
      { day: 13, passages: [{ bookId: "HEB", chapter: 11 }] },
      { day: 14, passages: [{ bookId: "REV", chapter: 21 }] },
    ],
  },
  {
    id: "genesis-7",
    name: "Creation Week",
    description: "Read Genesis 1-7 to understand beginnings",
    duration: 7,
    readings: [
      { day: 1, passages: [{ bookId: "GEN", chapter: 1 }] },
      { day: 2, passages: [{ bookId: "GEN", chapter: 2 }] },
      { day: 3, passages: [{ bookId: "GEN", chapter: 3 }] },
      { day: 4, passages: [{ bookId: "GEN", chapter: 4 }] },
      { day: 5, passages: [{ bookId: "GEN", chapter: 5 }] },
      { day: 6, passages: [{ bookId: "GEN", chapter: 6 }] },
      { day: 7, passages: [{ bookId: "GEN", chapter: 7 }] },
    ],
  },
  {
    id: "romans-road",
    name: "The Romans Road",
    description: "Understand salvation through Paul's letter to the Romans",
    duration: 16,
    readings: [
      { day: 1, passages: [{ bookId: "ROM", chapter: 1 }] },
      { day: 2, passages: [{ bookId: "ROM", chapter: 2 }] },
      { day: 3, passages: [{ bookId: "ROM", chapter: 3 }] },
      { day: 4, passages: [{ bookId: "ROM", chapter: 4 }] },
      { day: 5, passages: [{ bookId: "ROM", chapter: 5 }] },
      { day: 6, passages: [{ bookId: "ROM", chapter: 6 }] },
      { day: 7, passages: [{ bookId: "ROM", chapter: 7 }] },
      { day: 8, passages: [{ bookId: "ROM", chapter: 8 }] },
      { day: 9, passages: [{ bookId: "ROM", chapter: 9 }] },
      { day: 10, passages: [{ bookId: "ROM", chapter: 10 }] },
      { day: 11, passages: [{ bookId: "ROM", chapter: 11 }] },
      { day: 12, passages: [{ bookId: "ROM", chapter: 12 }] },
      { day: 13, passages: [{ bookId: "ROM", chapter: 13 }] },
      { day: 14, passages: [{ bookId: "ROM", chapter: 14 }] },
      { day: 15, passages: [{ bookId: "ROM", chapter: 15 }] },
      { day: 16, passages: [{ bookId: "ROM", chapter: 16 }] },
    ],
  },
  {
    id: "acts-28",
    name: "Acts of the Apostles",
    description: "Follow the early church from Jerusalem to Rome",
    duration: 28,
    readings: Array.from({ length: 28 }, (_, i) => ({
      day: i + 1,
      passages: [{ bookId: "ACT", chapter: i + 1 }],
    })),
  },
  {
    id: "wisdom-literature",
    name: "Wisdom Literature",
    description: "Ecclesiastes, Song of Solomon, and Job - life's big questions",
    duration: 21,
    readings: [
      // Ecclesiastes 1-12
      ...Array.from({ length: 12 }, (_, i) => ({
        day: i + 1,
        passages: [{ bookId: "ECC", chapter: i + 1 }],
      })),
      // Song of Solomon 1-8
      ...Array.from({ length: 8 }, (_, i) => ({
        day: i + 13,
        passages: [{ bookId: "SNG", chapter: i + 1 }],
      })),
      // Job highlights
      { day: 21, passages: [{ bookId: "JOB", chapter: 1 }, { bookId: "JOB", chapter: 2 }, { bookId: "JOB", chapter: 38 }, { bookId: "JOB", chapter: 42 }] },
    ],
  },
  {
    id: "sermon-on-mount",
    name: "Sermon on the Mount Deep Dive",
    description: "Spend a week in Jesus' most famous teaching (Matthew 5-7)",
    duration: 7,
    readings: [
      { day: 1, passages: [{ bookId: "MAT", chapter: 5 }] },
      { day: 2, passages: [{ bookId: "MAT", chapter: 5 }] }, // Re-read for depth
      { day: 3, passages: [{ bookId: "MAT", chapter: 6 }] },
      { day: 4, passages: [{ bookId: "MAT", chapter: 6 }] },
      { day: 5, passages: [{ bookId: "MAT", chapter: 7 }] },
      { day: 6, passages: [{ bookId: "MAT", chapter: 7 }] },
      { day: 7, passages: [{ bookId: "MAT", chapter: 5 }, { bookId: "MAT", chapter: 6 }, { bookId: "MAT", chapter: 7 }] },
    ],
  },
  {
    id: "prophets-intro",
    name: "Introduction to the Prophets",
    description: "Key chapters from Isaiah, Jeremiah, and Ezekiel",
    duration: 14,
    readings: [
      { day: 1, passages: [{ bookId: "ISA", chapter: 1 }] },
      { day: 2, passages: [{ bookId: "ISA", chapter: 6 }] },
      { day: 3, passages: [{ bookId: "ISA", chapter: 9 }] },
      { day: 4, passages: [{ bookId: "ISA", chapter: 40 }] },
      { day: 5, passages: [{ bookId: "ISA", chapter: 53 }] },
      { day: 6, passages: [{ bookId: "ISA", chapter: 55 }] },
      { day: 7, passages: [{ bookId: "JER", chapter: 1 }] },
      { day: 8, passages: [{ bookId: "JER", chapter: 29 }] },
      { day: 9, passages: [{ bookId: "JER", chapter: 31 }] },
      { day: 10, passages: [{ bookId: "LAM", chapter: 3 }] },
      { day: 11, passages: [{ bookId: "EZK", chapter: 1 }] },
      { day: 12, passages: [{ bookId: "EZK", chapter: 37 }] },
      { day: 13, passages: [{ bookId: "DAN", chapter: 3 }] },
      { day: 14, passages: [{ bookId: "DAN", chapter: 6 }] },
    ],
  },
  {
    id: "letters-to-churches",
    name: "Letters to Young Churches",
    description: "Galatians, Ephesians, Philippians, Colossians - Paul's prison epistles",
    duration: 20,
    readings: [
      // Galatians 1-6
      ...Array.from({ length: 6 }, (_, i) => ({
        day: i + 1,
        passages: [{ bookId: "GAL", chapter: i + 1 }],
      })),
      // Ephesians 1-6
      ...Array.from({ length: 6 }, (_, i) => ({
        day: i + 7,
        passages: [{ bookId: "EPH", chapter: i + 1 }],
      })),
      // Philippians 1-4
      ...Array.from({ length: 4 }, (_, i) => ({
        day: i + 13,
        passages: [{ bookId: "PHP", chapter: i + 1 }],
      })),
      // Colossians 1-4
      ...Array.from({ length: 4 }, (_, i) => ({
        day: i + 17,
        passages: [{ bookId: "COL", chapter: i + 1 }],
      })),
    ],
  },
  {
    id: "exodus-journey",
    name: "The Exodus Journey",
    description: "From slavery to Sinai - Israel's foundational story",
    duration: 21,
    readings: [
      { day: 1, passages: [{ bookId: "EXO", chapter: 1 }, { bookId: "EXO", chapter: 2 }] },
      { day: 2, passages: [{ bookId: "EXO", chapter: 3 }, { bookId: "EXO", chapter: 4 }] },
      { day: 3, passages: [{ bookId: "EXO", chapter: 5 }, { bookId: "EXO", chapter: 6 }] },
      { day: 4, passages: [{ bookId: "EXO", chapter: 7 }, { bookId: "EXO", chapter: 8 }] },
      { day: 5, passages: [{ bookId: "EXO", chapter: 9 }, { bookId: "EXO", chapter: 10 }] },
      { day: 6, passages: [{ bookId: "EXO", chapter: 11 }, { bookId: "EXO", chapter: 12 }] },
      { day: 7, passages: [{ bookId: "EXO", chapter: 13 }, { bookId: "EXO", chapter: 14 }] },
      { day: 8, passages: [{ bookId: "EXO", chapter: 15 }, { bookId: "EXO", chapter: 16 }] },
      { day: 9, passages: [{ bookId: "EXO", chapter: 17 }, { bookId: "EXO", chapter: 18 }] },
      { day: 10, passages: [{ bookId: "EXO", chapter: 19 }, { bookId: "EXO", chapter: 20 }] },
      { day: 11, passages: [{ bookId: "EXO", chapter: 21 }, { bookId: "EXO", chapter: 22 }] },
      { day: 12, passages: [{ bookId: "EXO", chapter: 23 }, { bookId: "EXO", chapter: 24 }] },
      { day: 13, passages: [{ bookId: "EXO", chapter: 25 }, { bookId: "EXO", chapter: 26 }] },
      { day: 14, passages: [{ bookId: "EXO", chapter: 27 }, { bookId: "EXO", chapter: 28 }] },
      { day: 15, passages: [{ bookId: "EXO", chapter: 29 }, { bookId: "EXO", chapter: 30 }] },
      { day: 16, passages: [{ bookId: "EXO", chapter: 31 }, { bookId: "EXO", chapter: 32 }] },
      { day: 17, passages: [{ bookId: "EXO", chapter: 33 }, { bookId: "EXO", chapter: 34 }] },
      { day: 18, passages: [{ bookId: "EXO", chapter: 35 }, { bookId: "EXO", chapter: 36 }] },
      { day: 19, passages: [{ bookId: "EXO", chapter: 37 }, { bookId: "EXO", chapter: 38 }] },
      { day: 20, passages: [{ bookId: "EXO", chapter: 39 }, { bookId: "EXO", chapter: 40 }] },
      { day: 21, passages: [{ bookId: "PSA", chapter: 105 }, { bookId: "PSA", chapter: 106 }] },
    ],
  },
  {
    id: "revelation-22",
    name: "Revelation Unveiled",
    description: "Journey through the final book of the Bible",
    duration: 22,
    readings: Array.from({ length: 22 }, (_, i) => ({
      day: i + 1,
      passages: [{ bookId: "REV", chapter: i + 1 }],
    })),
  },
  {
    id: "life-of-david",
    name: "The Life of David",
    description: "From shepherd boy to king - David's epic journey",
    duration: 14,
    readings: [
      { day: 1, passages: [{ bookId: "1SA", chapter: 16 }] },
      { day: 2, passages: [{ bookId: "1SA", chapter: 17 }] },
      { day: 3, passages: [{ bookId: "1SA", chapter: 18 }, { bookId: "1SA", chapter: 19 }] },
      { day: 4, passages: [{ bookId: "1SA", chapter: 20 }] },
      { day: 5, passages: [{ bookId: "1SA", chapter: 24 }] },
      { day: 6, passages: [{ bookId: "1SA", chapter: 31 }, { bookId: "2SA", chapter: 1 }] },
      { day: 7, passages: [{ bookId: "2SA", chapter: 5 }, { bookId: "2SA", chapter: 6 }] },
      { day: 8, passages: [{ bookId: "2SA", chapter: 7 }] },
      { day: 9, passages: [{ bookId: "2SA", chapter: 11 }, { bookId: "2SA", chapter: 12 }] },
      { day: 10, passages: [{ bookId: "PSA", chapter: 51 }] },
      { day: 11, passages: [{ bookId: "2SA", chapter: 15 }, { bookId: "2SA", chapter: 16 }] },
      { day: 12, passages: [{ bookId: "2SA", chapter: 18 }] },
      { day: 13, passages: [{ bookId: "2SA", chapter: 22 }] },
      { day: 14, passages: [{ bookId: "1KI", chapter: 1 }, { bookId: "1KI", chapter: 2 }] },
    ],
  },
];

export function getReadingPlanById(id: string): ReadingPlan | undefined {
  return READING_PLANS.find((plan) => plan.id === id);
}
