import type { StudyNotes } from "./types";

// Sample study notes demonstrating the system
// In production, these would be generated by AI or curated by scholars

export const SAMPLE_NOTES: Record<string, StudyNotes> = {
  "JHN.3": {
    passage: "John 3",
    context: {
      historical: "Jesus is early in His ministry, around 27-30 AD. The Jewish people are under Roman occupation, longing for a Messiah to deliver them politically. Religious leaders like Nicodemus held significant influence but were divided about Jesus.",
      cultural: "Pharisees like Nicodemus were deeply respected teachers who dedicated their lives to studying and obeying God's law. Coming to Jesus 'at night' may indicate caution about his reputation, or simply that nighttime was when rabbis typically held deep discussions.",
      literary: "John's Gospel is theological, focusing on who Jesus IS rather than just what He did. This conversation introduces key themes: new birth, belief, light vs. darkness, and God's love for the world.",
      geographic: "Likely in Jerusalem during Passover, when Jews from across Israel gathered to celebrate God's deliverance from Egypt - making Jesus' message of a 'new deliverance' especially meaningful.",
      audience: "John wrote primarily to help people believe that Jesus is the Christ, the Son of God (John 20:31). He assumes readers may not know Jewish customs, explaining them throughout.",
    },
    perspectives: {
      commonGround: [
        "God's love for humanity is central to the gospel message",
        "Salvation comes through faith in Jesus Christ",
        "Being 'born again' represents a genuine spiritual transformation",
        "Jesus came not to condemn but to save",
        "This passage reveals the heart of God toward all people",
      ],
      differentViews: [
        {
          view: "Baptismal regeneration - 'born of water' refers to baptism",
          traditions: ["Catholic", "Orthodox", "some Lutherans"],
          reasoning: "Water and Spirit together suggest the sacrament of baptism, which early church consistently connected to new birth",
          heartBehind: "Emphasizes that God works through tangible means of grace and the community of faith",
        },
        {
          view: "Natural birth - 'born of water' refers to physical birth",
          traditions: ["Many Baptists", "Evangelicals"],
          reasoning: "Jesus is contrasting physical birth with spiritual birth; 'water' refers to amniotic fluid or natural birth process",
          heartBehind: "Emphasizes that salvation is purely God's spiritual work, not dependent on human rituals",
        },
        {
          view: "Word and Spirit - 'water' symbolizes God's cleansing Word",
          traditions: ["Reformed", "Presbyterian"],
          reasoning: "Scripture often connects water with God's Word (Ephesians 5:26); the Spirit works through the Word",
          heartBehind: "Emphasizes the centrality of Scripture in conversion",
        },
      ],
      unityNote: "Despite different views on 'born of water,' all Christians agree that genuine faith in Jesus, enabled by the Holy Spirit, is essential for salvation. Our unity is in Christ, not in perfect agreement on every detail.",
    },
    deepDive: {
      keyWords: [
        {
          word: "Born again",
          original: "γεννηθῇ ἄνωθεν (gennēthē anōthen)",
          meaning: "Can mean 'born again' OR 'born from above' - a deliberate double meaning",
          significance: "Jesus speaks of heavenly realities; Nicodemus thinks earthly. The misunderstanding reveals the need for spiritual eyes to see spiritual truth.",
        },
        {
          word: "World",
          original: "κόσμος (kosmos)",
          meaning: "The entire created order, especially humanity in its fallen state",
          significance: "God's love isn't limited to Israel - it encompasses all peoples, nations, and cultures. Revolutionary for a Jewish audience.",
        },
        {
          word: "Believes",
          original: "πιστεύων (pisteuōn)",
          meaning: "Present active participle - ongoing, active trust",
          significance: "Not just a one-time decision, but a continuous posture of trusting, relying on, committing to Jesus.",
        },
        {
          word: "Eternal life",
          original: "ζωὴν αἰώνιον (zōēn aiōnion)",
          meaning: "Not just 'life that lasts forever' but 'life of the age to come' - quality AND quantity",
          significance: "Eternal life begins NOW for believers - it's knowing God (John 17:3), not just existing forever.",
        },
      ],
      crossReferences: [
        { reference: "Numbers 21:4-9", connection: "The bronze serpent Jesus references - looking in faith brought healing, just as looking to the lifted-up Christ brings salvation" },
        { reference: "Ezekiel 36:25-27", connection: "God's promise to sprinkle clean water and give a new heart and Spirit - the new birth Jesus describes" },
        { reference: "1 John 4:9-10", connection: "John later reflects: 'This is how God showed His love... He sent His Son as an atoning sacrifice'" },
        { reference: "Romans 5:8", connection: "Paul echoes: 'God demonstrates His own love for us in this: while we were still sinners, Christ died for us'" },
      ],
      themes: [
        "God's Love",
        "New Birth / Regeneration",
        "Faith and Belief",
        "Light vs. Darkness",
        "Salvation",
        "The Son of God",
        "Eternal Life",
        "The Holy Spirit",
      ],
      symbols: [
        { symbol: "Wind", meaning: "The Holy Spirit - invisible but powerful, sovereign in His movement, bringing life" },
        { symbol: "Light", meaning: "Truth, goodness, God's presence; those who love light come to Jesus" },
        { symbol: "Darkness", meaning: "Sin, evil, hiding from God; those who love darkness avoid the light" },
        { symbol: "Lifted up serpent", meaning: "Foreshadowing the cross - just as looking at the serpent brought physical healing, looking to Christ brings spiritual salvation" },
      ],
    },
    application: {
      thenAndNow: {
        originalMeaning: "Nicodemus, despite his religious knowledge and moral life, needed a complete spiritual rebirth. Religion and rule-following weren't enough - he needed to be transformed by God's Spirit from the inside out.",
        modernApplication: "We too can be 'good people' who attend church, know the Bible, and follow moral rules - yet still need the new birth. It's not about religious performance but heart transformation. And God's love extends to everyone, not just those who seem 'deserving.'",
      },
      reflectionQuestions: [
        "Have I experienced a genuine spiritual rebirth, or am I relying on religious activity?",
        "Do I truly believe God loves the WHOLE world - including people very different from me?",
        "Am I walking in the light, or are there areas of my life I'm hiding from God?",
        "How does knowing that God sent Jesus to SAVE, not condemn, change how I approach Him?",
        "Who in my life needs to hear that God loves them?",
      ],
      prayerPrompt: "Father, thank You for loving the world so much that You gave Your only Son. Help me to truly believe - not just mentally agree, but actively trust my whole life to Jesus. Search my heart and show me any areas still in darkness. Give me Your heart for the people around me who don't yet know Your love. In Jesus' name, Amen.",
      actionStep: "This week, share with one person (in word or action) that God loves them. It might be a friend who feels unlovable, a family member who's wandered from faith, or a stranger who needs kindness.",
    },
    connections: {
      relatedStories: [
        "Zacchaeus (Luke 19) - Another religious outsider who encountered Jesus personally",
        "The Woman at the Well (John 4) - Jesus offers 'living water' to an unlikely person",
        "Paul's Conversion (Acts 9) - A religious expert who needed radical transformation",
      ],
      prophecyLinks: [
        {
          oldTestament: "Isaiah 9:6-7",
          newTestament: "John 3:16",
          connection: "The promised Son who would rule forever is revealed as God's gift of love to the world",
        },
        {
          oldTestament: "Genesis 22:2 - Abraham's only son",
          newTestament: "John 3:16 - God's only Son",
          connection: "What God asked Abraham to do (but stopped), God Himself did - offering His own Son",
        },
      ],
      jesusConnection: "This passage is the heartbeat of the gospel: Jesus is the eternal Son of God, sent not as a condemning judge but as a loving Savior. His being 'lifted up' points to the cross, where He would die for the sins of the world. Through Him, anyone who believes receives eternal life.",
      bigPicture: "John 3 answers the fundamental human question: How can I be right with God? Not through religious effort (even Nicodemus couldn't earn it), but through God's initiative of love. This chapter connects Creation (God's love for the world He made), Fall (humans in darkness needing salvation), and Redemption (the Son given to save). It points forward to the cross and ultimately to new creation, where those born of the Spirit live forever with God.",
    },
    difficultQuestions: [
      {
        question: "What about people who never hear about Jesus?",
        honestAnswer: "Scripture doesn't give us a complete answer. We know God is just AND loving. Some passages suggest God judges based on the light people have received (Romans 2:12-16). What we know for certain: the gospel is for ALL people, and we're called to share it.",
        whatWeKnow: "God desires all to be saved (1 Tim 2:4). Jesus is the only way (John 14:6). God is perfectly just and merciful.",
        whatWeTrust: "God will do right (Genesis 18:25). His judgments are true and righteous. Our job is to share the good news, not to limit God's mercy.",
      },
      {
        question: "Why does God require belief? Isn't that unfair?",
        honestAnswer: "Belief isn't an arbitrary requirement - it's the nature of relationship. You can't have a relationship with someone you refuse to trust. God has made Himself known; faith is simply our response to His initiative.",
        whatWeKnow: "God takes the first step (He loved, He gave, He sent). Faith is a gift made possible by grace. God desires relationship, not forced compliance.",
        whatWeTrust: "God's requirements flow from His character of love. He has made the way accessible through Jesus. His Spirit enables genuine faith.",
      },
    ],
  },

  "GEN.1": {
    passage: "Genesis 1",
    context: {
      historical: "Written to Israel, likely during or after the Exodus, when they were surrounded by nations with competing creation stories. Egyptian and Babylonian myths featured chaotic battles between gods. Genesis presents one sovereign God creating peacefully by His word.",
      cultural: "Ancient Near Eastern cultures worshipped the sun, moon, and stars as gods. Genesis deliberately 'demotes' them - they're just lights that God made on Day 4. The creation account is subtly but powerfully counter-cultural.",
      literary: "Genesis 1 is highly structured and poetic, with parallel days (1-3 forming/4-6 filling) and repeated refrains ('And God said... and it was so... and it was good'). It reads like a hymn of praise to the Creator.",
      audience: "Israelites who had been slaves in Egypt, surrounded by polytheistic religions. They needed to know: Who is the true God? What is humanity's place? Why does the world exist?",
    },
    perspectives: {
      commonGround: [
        "God is the sole Creator of everything that exists",
        "Creation was intentional, not accidental",
        "Humans are uniquely made in God's image",
        "Creation was originally 'very good'",
        "God is sovereign over all He has made",
        "The Sabbath pattern is established by God",
      ],
      differentViews: [
        {
          view: "Young Earth Creation - six literal 24-hour days",
          traditions: ["Many Evangelicals", "Fundamentalists", "some Reformed"],
          reasoning: "The Hebrew word 'yom' with a number typically means a 24-hour day; straightforward reading of the text",
          heartBehind: "Deep commitment to biblical authority and taking Scripture at face value",
        },
        {
          view: "Old Earth Creation - 'days' as long ages",
          traditions: ["Many Catholics", "Orthodox", "some Evangelicals"],
          reasoning: "A 'day' to God is like a thousand years (2 Pet 3:8); allows harmony with scientific evidence",
          heartBehind: "Honoring both Scripture and God's revelation in nature",
        },
        {
          view: "Literary Framework - structured theology, not chronology",
          traditions: ["Many Reformed scholars", "some Catholics"],
          reasoning: "The parallel structure (days 1-3/4-6) suggests theological organization rather than strict sequence",
          heartBehind: "Reading Genesis in its ancient literary context",
        },
      ],
      unityNote: "Christians disagree on HOW and WHEN God created, but agree on WHO and WHY: the one true God intentionally created everything, including humans in His image, and called it good. Our unity is in the Creator, not in a particular scientific interpretation.",
    },
    deepDive: {
      keyWords: [
        {
          word: "Create",
          original: "בָּרָא (bara)",
          meaning: "To create something new; in the Bible, only God is the subject of 'bara'",
          significance: "This word emphasizes God's unique ability to bring into being something that didn't exist before.",
        },
        {
          word: "Image of God",
          original: "צֶלֶם אֱלֹהִים (tselem Elohim)",
          meaning: "Image, likeness, representation - like a statue representing a king",
          significance: "Humans uniquely represent God on earth - we have dignity, responsibility, and capacity for relationship with Him.",
        },
        {
          word: "Good",
          original: "טוֹב (tov)",
          meaning: "Good, beautiful, fitting, functioning as intended",
          significance: "Creation reflects God's character. Evil and suffering are intrusions, not part of God's original design.",
        },
      ],
      crossReferences: [
        { reference: "John 1:1-3", connection: "The Word (Jesus) was present at creation - 'through Him all things were made'" },
        { reference: "Colossians 1:16-17", connection: "All things created through Christ and for Christ; He holds all things together" },
        { reference: "Hebrews 11:3", connection: "By faith we understand that the universe was formed at God's command" },
        { reference: "Revelation 21:1", connection: "The story ends with new creation - God making all things new" },
      ],
      themes: [
        "God's Sovereignty",
        "The Power of God's Word",
        "Order from Chaos",
        "Human Dignity",
        "Sabbath Rest",
        "Goodness of Creation",
      ],
      symbols: [
        { symbol: "Light", meaning: "God's presence, truth, life - the first thing God creates before anything else" },
        { symbol: "Waters/Deep", meaning: "Ancient symbol of chaos; God's Spirit hovers over it, bringing order" },
        { symbol: "Breath/Spirit", meaning: "Hebrew 'ruach' - God's Spirit is present and active in creation" },
      ],
    },
    application: {
      thenAndNow: {
        originalMeaning: "Israel needed to know that their God - not the Egyptian or Canaanite gods - was the true Creator of everything. The sun wasn't a god; it was a lamp God made. They had worth because they bore God's image, not because Pharaoh said so.",
        modernApplication: "We live in a culture that often sees humans as accidents of nature or as consumers to be marketed to. Genesis says we have inherent dignity as God's image-bearers. Creation isn't just resources to exploit but a good gift to steward. And the Sabbath rhythm reminds us we're not machines - rest is part of God's design.",
      },
      reflectionQuestions: [
        "Do I live as if I'm an accident, or as someone made in God's image with purpose?",
        "How do I treat creation - as something to exploit or as a gift to steward?",
        "Do I practice Sabbath rest, or am I always producing?",
        "What does it mean that I'm made to represent God to the world around me?",
      ],
      prayerPrompt: "Creator God, thank You for making me in Your image. Help me see my own dignity and the dignity of every person I meet today. Forgive me for the ways I've failed to care for Your creation. Teach me the rhythm of work and rest that You designed. May my life reflect Your goodness. Amen.",
      actionStep: "Practice Sabbath this week - set aside time to rest, worship, and enjoy God's creation without producing or consuming. Simply be a creature enjoying the Creator.",
    },
    connections: {
      relatedStories: [
        "Psalm 104 - A poetic celebration of creation",
        "Job 38-41 - God reveals Himself through creation",
        "Revelation 21-22 - New creation, the story comes full circle",
      ],
      prophecyLinks: [
        {
          oldTestament: "Genesis 1:26 - Humanity made in God's image",
          newTestament: "Colossians 1:15 - Christ is the image of the invisible God",
          connection: "Jesus is the perfect image of God that humanity was always meant to reflect",
        },
      ],
      jesusConnection: "John 1 reveals that Jesus, the Word, was the agent of creation - 'through Him all things were made.' The same Word that spoke light into darkness spoke hope into our darkness. And just as God rested on the seventh day, Jesus offers us rest for our souls (Matthew 11:28).",
      bigPicture: "Genesis 1 is the opening scene of the Bible's story. A good God creates a good world and places humanity in it as His representatives. This sets up the tragedy of Genesis 3 (the Fall), the long journey of redemption, and the ultimate hope of Revelation 21-22 where God makes all things new. Everything in Scripture flows from and back to creation.",
    },
  },

  "MAT.5": {
    passage: "Matthew 5 (Sermon on the Mount)",
    context: {
      historical: "Jesus speaks early in His Galilean ministry, around 28-30 AD. He has begun calling disciples and His fame is spreading throughout Israel. This sermon establishes His authority as a teacher greater than Moses.",
      cultural: "Jewish teachers typically sat to teach formally. The 'mountain' echoes Moses receiving the Law on Mount Sinai. Jesus' audience lived under Roman occupation, heavily taxed, with limited rights - making His teachings on blessing, peacemaking, and enemy-love revolutionary.",
      literary: "The Sermon on the Mount (Matthew 5-7) is the first of five major teaching blocks in Matthew, structured to present Jesus as a new Moses giving a new Torah. The Beatitudes open with blessings, reversing worldly values.",
      geographic: "The traditional site is a hillside near Capernaum overlooking the Sea of Galilee. This region was Jesus' primary ministry area, where many disciples came from.",
      audience: "Primarily Jesus' disciples, but with crowds listening (Matthew 5:1, 7:28). Matthew wrote for Jewish Christians, showing how Jesus fulfills rather than abolishes the Law.",
    },
    perspectives: {
      commonGround: [
        "The Beatitudes reveal the values of God's kingdom",
        "Jesus calls His followers to a righteousness that exceeds external rule-keeping",
        "Love for enemies is central to Christian ethics",
        "Jesus has authority to interpret and intensify the Law",
        "This sermon describes the character of kingdom citizens",
      ],
      differentViews: [
        {
          view: "Blueprint for Christian living - these commands are for all believers today",
          traditions: ["Anabaptist", "Wesleyan", "many Evangelicals"],
          reasoning: "Jesus commands obedience (7:24-27); the Sermon describes how His followers should live",
          heartBehind: "Taking Jesus' words seriously as direct commands for daily life",
        },
        {
          view: "Impossible ideal - showing our need for grace",
          traditions: ["Lutheran", "some Reformed"],
          reasoning: "The demands are impossible (be perfect, 5:48) to drive us to rely on Christ's righteousness alone",
          heartBehind: "Emphasizing grace and Christ's work rather than human achievement",
        },
        {
          view: "Kingdom ethics - describing life in the age to come, beginning now",
          traditions: ["Catholic", "Orthodox", "many Protestants"],
          reasoning: "The Sermon describes kingdom values that disciples begin living now but will be fully realized in the new creation",
          heartBehind: "Balancing 'already' and 'not yet' aspects of God's kingdom",
        },
      ],
      unityNote: "All Christians agree the Sermon reveals God's heart, exposes our need for grace, and calls us to transformed living. Whether we emphasize obedience, grace, or kingdom hope, we're responding to the same Jesus.",
    },
    deepDive: {
      keyWords: [
        {
          word: "Blessed",
          original: "μακάριοι (makarioi)",
          meaning: "Fortunate, happy, to be envied - not just a future promise but a present reality",
          significance: "Jesus pronounces blessing on those the world considers cursed - the poor, mourning, meek. God's values invert worldly status.",
        },
        {
          word: "Poor in spirit",
          original: "πτωχοὶ τῷ πνεύματι (ptōchoi tō pneumati)",
          meaning: "Spiritually bankrupt, recognizing one's complete need for God",
          significance: "The kingdom belongs to those who know they have nothing to offer - the opposite of religious pride.",
        },
        {
          word: "Fulfill",
          original: "πληρῶσαι (plērōsai)",
          meaning: "To fill full, complete, bring to intended goal",
          significance: "Jesus doesn't abolish the Law but brings it to its fullest meaning and intended purpose.",
        },
      ],
      crossReferences: [
        { reference: "Exodus 20:1-17", connection: "The Ten Commandments - Jesus intensifies them, addressing heart as well as actions" },
        { reference: "Leviticus 19:18", connection: "'Love your neighbor' - Jesus expands 'neighbor' to include enemies" },
        { reference: "Isaiah 61:1-3", connection: "Good news to the poor, comfort for mourners - Jesus embodies this prophecy" },
        { reference: "Micah 6:8", connection: "Act justly, love mercy, walk humbly - the Beatitudes echo prophetic values" },
        { reference: "Romans 12:14-21", connection: "Paul applies Jesus' teaching on blessing enemies and overcoming evil with good" },
        { reference: "James 2:5", connection: "James echoes: 'Has not God chosen the poor in the world to be rich in faith?'" },
      ],
      themes: [
        "The Kingdom of Heaven",
        "Righteousness",
        "Transformation of the Heart",
        "Love (including enemies)",
        "Law and Grace",
        "Salt and Light",
        "Prayer",
        "Peacemaking",
      ],
      symbols: [
        { symbol: "Salt", meaning: "Preservation, seasoning, covenant faithfulness - disciples preserve society and add 'flavor' to life" },
        { symbol: "Light", meaning: "God's truth, goodness, and presence shining through His people to expose darkness" },
        { symbol: "Mountain", meaning: "Place of divine revelation, echoing Mount Sinai where Moses received the Law" },
      ],
    },
    application: {
      thenAndNow: {
        originalMeaning: "Jesus established that kingdom citizenship isn't about external compliance but internal transformation. To Jewish hearers expecting a political Messiah, He described a kingdom of humility, mercy, and enemy-love - shocking in an occupied land.",
        modernApplication: "We live in a culture that celebrates power, winning, and defeating enemies. Jesus still calls us to a counter-cultural life: blessing those who curse us, seeking reconciliation before worship, loving those who seem unlovable. This isn't weakness - it's the power of the kingdom.",
      },
      reflectionQuestions: [
        "Which Beatitude challenges me most? Why?",
        "Am I more focused on external religious behavior or internal heart transformation?",
        "Who is my 'enemy' that Jesus calls me to love?",
        "Where do I need to be 'salt and light' in my community?",
        "Is my righteousness based on rule-keeping or on knowing Christ?",
      ],
      prayerPrompt: "Lord Jesus, I confess that my heart falls short of Your kingdom values. Make me poor in spirit - aware of my need for You. Help me mourn over sin, pursue meekness, hunger for righteousness. Transform my heart so that mercy, purity, and peacemaking flow naturally. Teach me to love even my enemies. In Your name, Amen.",
      actionStep: "Identify one person you find difficult to love. This week, pray for them daily and look for one concrete way to bless them.",
    },
    connections: {
      relatedStories: [
        "Moses on Mount Sinai (Exodus 19-20) - the first giving of the Law",
        "David's Psalms of Blessing (Psalm 1, 32, 128) - earlier 'beatitude' language",
        "The Good Samaritan (Luke 10) - Jesus illustrating love for 'enemies'",
      ],
      prophecyLinks: [
        {
          oldTestament: "Isaiah 61:1-2",
          newTestament: "Matthew 5:3-4",
          connection: "Isaiah's promise of good news to the poor and comfort for mourners finds fulfillment in Jesus' opening words",
        },
        {
          oldTestament: "Jeremiah 31:31-33",
          newTestament: "Matthew 5:17-20",
          connection: "The new covenant with law written on hearts is what Jesus teaches - transformation from within",
        },
      ],
      jesusConnection: "The Sermon on the Mount isn't just about what we must do - it's about who Jesus is. He is the One who fulfills the Law perfectly, embodies the Beatitudes fully, and gives us His Spirit to live this way. We follow the Sermon by following Him.",
      bigPicture: "God gave the Law through Moses to show Israel how to live as His people. But the Law could only reveal sin, not transform hearts. Jesus comes as a greater Moses, not giving a new Law but fulfilling the old one and offering the Spirit who enables transformed living. The Sermon describes citizens of the kingdom that Jesus inaugurates - a kingdom of mercy, peace, and love that will one day cover the earth.",
    },
    difficultQuestions: [
      {
        question: "Isn't 'turn the other cheek' just letting people abuse you?",
        honestAnswer: "Jesus isn't commanding passivity in the face of evil. In context, a slap on the right cheek was an insult, not assault. Jesus calls us to respond to insults without retaliation - breaking the cycle of revenge. This isn't the same as allowing ongoing abuse; Jesus Himself confronted evil directly.",
        whatWeKnow: "Jesus was not passive - He overturned tables, rebuked hypocrites, and challenged injustice. The principle is non-retaliation for personal insults, not permission for ongoing harm.",
        whatWeTrust: "God is the ultimate Judge. When we refuse retaliation, we trust Him to make things right. This frees us from the prison of bitterness.",
      },
      {
        question: "How can anyone 'be perfect as your heavenly Father is perfect'?",
        honestAnswer: "The Greek word 'teleios' means mature, complete, whole - not sinless perfection. In context (5:43-48), it means loving completely, not just those who love you. It's a direction, not a destination we achieve in this life.",
        whatWeKnow: "No human achieves sinless perfection (1 John 1:8). Jesus is the only one who perfectly embodied these teachings. We grow in maturity through the Spirit.",
        whatWeTrust: "God looks at the heart's direction, not just the destination. He gives grace for the journey and will complete His work in us (Philippians 1:6).",
      },
    ],
  },

  "ROM.8": {
    passage: "Romans 8",
    context: {
      historical: "Paul writes to the church in Rome around 57 AD, a congregation he has never visited. The Roman church included both Jewish and Gentile believers navigating their relationship. This letter systematically presents the gospel.",
      cultural: "Rome was the center of the empire - powerful, diverse, and morally complex. Christians there faced social pressure as a small, misunderstood group. The themes of slavery and adoption would resonate deeply in a culture where both were common.",
      literary: "Romans 8 is the climax of Paul's argument about salvation. Chapters 1-3 establish universal sin, 4-5 explain justification by faith, 6-7 address the struggle with sin, and chapter 8 celebrates life in the Spirit. It's often called the greatest chapter in the Bible.",
      audience: "Mixed Jewish and Gentile believers in Rome who needed to understand how God's promises to Israel relate to faith in Christ, and how believers should live in a hostile world.",
    },
    perspectives: {
      commonGround: [
        "There is no condemnation for those in Christ Jesus",
        "The Holy Spirit dwells in all believers",
        "Nothing can separate us from God's love in Christ",
        "Believers are adopted as God's children",
        "Present sufferings are not worth comparing with future glory",
        "The Spirit helps us in our weakness",
      ],
      differentViews: [
        {
          view: "Predestination as God's unconditional choice of individuals",
          traditions: ["Reformed", "Calvinist"],
          reasoning: "Foreknew, predestined, called, justified, glorified (v.29-30) - an unbroken chain of God's sovereign action",
          heartBehind: "Emphasizing that salvation is entirely God's work, giving complete assurance to believers",
        },
        {
          view: "Predestination based on God's foreknowledge of faith",
          traditions: ["Arminian", "Wesleyan", "some Baptists"],
          reasoning: "God 'foreknew' those who would believe and predestined them to be conformed to Christ",
          heartBehind: "Preserving human responsibility and the genuine offer of salvation to all",
        },
        {
          view: "Corporate election - God predestined the church as a body",
          traditions: ["some Evangelical scholars"],
          reasoning: "The focus is on God's plan for His people as a whole, conforming them to Christ's image",
          heartBehind: "Emphasizing the communal nature of salvation and God's redemptive plan",
        },
      ],
      unityNote: "Whatever view believers hold on predestination, all agree on the result: those in Christ are secure, loved, and destined for glory. The debate is about how we got here, not about whether we're safe in Christ.",
    },
    deepDive: {
      keyWords: [
        {
          word: "Condemnation",
          original: "κατάκριμα (katakrima)",
          meaning: "Adverse sentence, judicial verdict of guilt",
          significance: "The court has ruled - believers are declared 'not guilty.' This isn't pretending sin didn't happen but a real verdict based on Christ's sacrifice.",
        },
        {
          word: "Adoption",
          original: "υἱοθεσία (huiothesia)",
          meaning: "Placement as a son, legal adoption with full rights",
          significance: "In Roman culture, adopted sons had identical rights to biological sons. We are not second-class children - we are fully God's heirs.",
        },
        {
          word: "Groaning",
          original: "στενάζω (stenazō)",
          meaning: "To sigh, groan, expressing deep longing or distress",
          significance: "Creation groans (v.22), we groan (v.23), the Spirit groans (v.26) - all longing for the completion of redemption. Pain is real but not final.",
        },
        {
          word: "Intercedes",
          original: "ἐντυγχάνω (entynchanō)",
          meaning: "To meet with, appeal to, plead on behalf of",
          significance: "Both the Spirit (v.26-27) and Christ (v.34) intercede for us. We are never alone in our weakness or accusation.",
        },
      ],
      crossReferences: [
        { reference: "Genesis 3:17-19", connection: "Creation cursed because of sin - Romans 8:20-21 promises its liberation" },
        { reference: "Isaiah 50:8-9", connection: "The Servant's confidence: 'Who will bring charges?' - echoed in Romans 8:33" },
        { reference: "John 14:16-17", connection: "Jesus promises the Spirit who will dwell with and in believers" },
        { reference: "Galatians 4:4-7", connection: "Paul's parallel teaching on adoption and crying 'Abba, Father'" },
        { reference: "Philippians 1:6", connection: "He who began a good work will complete it - echoing Romans 8:29-30" },
        { reference: "1 John 3:1-2", connection: "See what love the Father has given - we are God's children, and will be like Christ" },
      ],
      themes: [
        "No Condemnation",
        "Life in the Spirit",
        "Adoption as Children",
        "Future Glory",
        "Suffering and Hope",
        "God's Sovereignty",
        "Intercession",
        "Inseparable Love",
      ],
      symbols: [
        { symbol: "Firstfruits", meaning: "The Spirit is the initial installment of our full inheritance - a guarantee of what's coming" },
        { symbol: "Abba", meaning: "Aramaic for 'Father' - intimate, familial address showing our close relationship with God" },
        { symbol: "Heirs", meaning: "Legal recipients of an inheritance - we share in Christ's inheritance of all things" },
      ],
    },
    application: {
      thenAndNow: {
        originalMeaning: "Roman Christians facing potential persecution, social ostracism, and daily temptation needed assurance: nothing could separate them from God's love. Their suffering wasn't meaningless but was working toward glory. The Spirit empowered what the Law could not.",
        modernApplication: "We too face suffering, doubt, and the nagging fear that we're not good enough. Romans 8 speaks to our deepest fears: you are not condemned, you are God's child, your suffering has purpose, and absolutely nothing can separate you from His love. This isn't positive thinking - it's the declaration of the Judge of the universe.",
      },
      reflectionQuestions: [
        "Do I truly believe there is NO condemnation for me in Christ, or do I still carry guilt?",
        "Am I living by the flesh (human effort) or the Spirit?",
        "How does knowing I'm God's adopted child change how I approach Him?",
        "What present suffering do I need to see in light of future glory?",
        "Is there anything I fear could separate me from God's love?",
      ],
      prayerPrompt: "Abba, Father - thank You that I can call You this. Thank You that there is no condemnation for me in Christ. When I feel accused, remind me that You are for me. When I suffer, help me trust that You are working all things together for good. When I'm too weak to pray, thank You that Your Spirit intercedes. Nothing can separate me from Your love. In Jesus' name, Amen.",
      actionStep: "Write out Romans 8:38-39 and put it somewhere you'll see it daily. When fear or condemnation arises this week, read it aloud as a declaration of truth.",
    },
    connections: {
      relatedStories: [
        "The Exodus (Exodus 14) - God's people delivered from slavery, now freed from sin's slavery",
        "Joseph's story (Genesis 50:20) - God working evil into good, like Romans 8:28",
        "Job's restoration (Job 42) - suffering leading to greater glory",
      ],
      prophecyLinks: [
        {
          oldTestament: "Ezekiel 36:26-27",
          newTestament: "Romans 8:9-11",
          connection: "The promise of God's Spirit dwelling within - now fulfilled in believers",
        },
        {
          oldTestament: "Isaiah 65:17-25",
          newTestament: "Romans 8:19-21",
          connection: "New heavens and new earth where creation is restored - the liberation we await",
        },
      ],
      jesusConnection: "Christ is central throughout: we are 'in Christ Jesus' (v.1), the Spirit is the 'Spirit of Christ' (v.9), we are 'co-heirs with Christ' (v.17), we are 'conformed to the image of Christ' (v.29), and Christ intercedes for us (v.34). Every promise of Romans 8 flows from union with Jesus.",
      bigPicture: "Romans 8 completes the arc of salvation. Humanity sinned (Rom 1-3), was justified by faith (4-5), struggles with sin (6-7), but now lives in the Spirit with assured hope (8). The chapter looks back to creation's fall, looks around at present suffering, and looks forward to final glory. It's the gospel in miniature: no condemnation, present help, and future hope - all secured by inseparable love.",
    },
    difficultQuestions: [
      {
        question: "If God works all things for good, why do terrible things happen?",
        honestAnswer: "Paul doesn't say all things ARE good, but that God works them TOGETHER for good. Evil is real and grieves God. But He is able to weave even tragedy into His redemptive purposes. This is not explanation but promise - ultimately, for those who love God, nothing is wasted.",
        whatWeKnow: "God is good. Evil exists. God will judge evil. He is able to bring good from bad. The cross itself - the worst event in history - brought our salvation.",
        whatWeTrust: "God sees what we cannot. His 'good' may not be our comfort but our Christlikeness (v.29). One day we'll understand; today we trust.",
      },
      {
        question: "How can I know if I'm truly 'in Christ' and not condemned?",
        honestAnswer: "The chapter gives markers: being led by the Spirit, experiencing the Spirit's witness that we're God's children, longing for redemption. But the basis isn't our performance - it's Christ's finished work. Assurance comes from looking to Him, not measuring ourselves.",
        whatWeKnow: "Faith in Christ is the entry point (Romans 3-5). The Spirit's presence confirms it. Ongoing trust in Christ maintains it. Self-examination has a place, but Christ is our assurance.",
        whatWeTrust: "If you're concerned about whether you're truly saved, that very concern often indicates the Spirit's work. Rest in Christ's promise, not your feelings.",
      },
    ],
  },
};

// Helper to get study notes for a passage
export function getStudyNotes(bookId: string, chapter: number): StudyNotes | null {
  const key = `${bookId}.${chapter}`;
  return SAMPLE_NOTES[key] || null;
}
