import type { StudyNotes } from "./types";

// Sample study notes demonstrating the system
// In production, these would be generated by AI or curated by scholars

export const SAMPLE_NOTES: Record<string, StudyNotes> = {
  "JHN.3": {
    passage: "John 3",
    context: {
      historical: "Jesus is early in His ministry, around 27-30 AD. The Jewish people are under Roman occupation, longing for a Messiah to deliver them politically. Religious leaders like Nicodemus held significant influence but were divided about Jesus.",
      cultural: "Pharisees like Nicodemus were deeply respected teachers who dedicated their lives to studying and obeying God's law. Coming to Jesus 'at night' may indicate caution about his reputation, or simply that nighttime was when rabbis typically held deep discussions.",
      literary: "John's Gospel is theological, focusing on who Jesus IS rather than just what He did. This conversation introduces key themes: new birth, belief, light vs. darkness, and God's love for the world.",
      geographic: "Likely in Jerusalem during Passover, when Jews from across Israel gathered to celebrate God's deliverance from Egypt - making Jesus' message of a 'new deliverance' especially meaningful.",
      audience: "John wrote primarily to help people believe that Jesus is the Christ, the Son of God (John 20:31). He assumes readers may not know Jewish customs, explaining them throughout.",
    },
    perspectives: {
      commonGround: [
        "God's love for humanity is central to the gospel message",
        "Salvation comes through faith in Jesus Christ",
        "Being 'born again' represents a genuine spiritual transformation",
        "Jesus came not to condemn but to save",
        "This passage reveals the heart of God toward all people",
      ],
      differentViews: [
        {
          view: "Baptismal regeneration - 'born of water' refers to baptism",
          traditions: ["Catholic", "Orthodox", "some Lutherans"],
          reasoning: "Water and Spirit together suggest the sacrament of baptism, which early church consistently connected to new birth",
          heartBehind: "Emphasizes that God works through tangible means of grace and the community of faith",
        },
        {
          view: "Natural birth - 'born of water' refers to physical birth",
          traditions: ["Many Baptists", "Evangelicals"],
          reasoning: "Jesus is contrasting physical birth with spiritual birth; 'water' refers to amniotic fluid or natural birth process",
          heartBehind: "Emphasizes that salvation is purely God's spiritual work, not dependent on human rituals",
        },
        {
          view: "Word and Spirit - 'water' symbolizes God's cleansing Word",
          traditions: ["Reformed", "Presbyterian"],
          reasoning: "Scripture often connects water with God's Word (Ephesians 5:26); the Spirit works through the Word",
          heartBehind: "Emphasizes the centrality of Scripture in conversion",
        },
      ],
      unityNote: "Despite different views on 'born of water,' all Christians agree that genuine faith in Jesus, enabled by the Holy Spirit, is essential for salvation. Our unity is in Christ, not in perfect agreement on every detail.",
    },
    deepDive: {
      keyWords: [
        {
          word: "Born again",
          original: "γεννηθῇ ἄνωθεν (gennēthē anōthen)",
          meaning: "Can mean 'born again' OR 'born from above' - a deliberate double meaning",
          significance: "Jesus speaks of heavenly realities; Nicodemus thinks earthly. The misunderstanding reveals the need for spiritual eyes to see spiritual truth.",
        },
        {
          word: "World",
          original: "κόσμος (kosmos)",
          meaning: "The entire created order, especially humanity in its fallen state",
          significance: "God's love isn't limited to Israel - it encompasses all peoples, nations, and cultures. Revolutionary for a Jewish audience.",
        },
        {
          word: "Believes",
          original: "πιστεύων (pisteuōn)",
          meaning: "Present active participle - ongoing, active trust",
          significance: "Not just a one-time decision, but a continuous posture of trusting, relying on, committing to Jesus.",
        },
        {
          word: "Eternal life",
          original: "ζωὴν αἰώνιον (zōēn aiōnion)",
          meaning: "Not just 'life that lasts forever' but 'life of the age to come' - quality AND quantity",
          significance: "Eternal life begins NOW for believers - it's knowing God (John 17:3), not just existing forever.",
        },
      ],
      crossReferences: [
        { reference: "Numbers 21:4-9", connection: "The bronze serpent Jesus references - looking in faith brought healing, just as looking to the lifted-up Christ brings salvation" },
        { reference: "Ezekiel 36:25-27", connection: "God's promise to sprinkle clean water and give a new heart and Spirit - the new birth Jesus describes" },
        { reference: "1 John 4:9-10", connection: "John later reflects: 'This is how God showed His love... He sent His Son as an atoning sacrifice'" },
        { reference: "Romans 5:8", connection: "Paul echoes: 'God demonstrates His own love for us in this: while we were still sinners, Christ died for us'" },
      ],
      themes: [
        "God's Love",
        "New Birth / Regeneration",
        "Faith and Belief",
        "Light vs. Darkness",
        "Salvation",
        "The Son of God",
        "Eternal Life",
        "The Holy Spirit",
      ],
      symbols: [
        { symbol: "Wind", meaning: "The Holy Spirit - invisible but powerful, sovereign in His movement, bringing life" },
        { symbol: "Light", meaning: "Truth, goodness, God's presence; those who love light come to Jesus" },
        { symbol: "Darkness", meaning: "Sin, evil, hiding from God; those who love darkness avoid the light" },
        { symbol: "Lifted up serpent", meaning: "Foreshadowing the cross - just as looking at the serpent brought physical healing, looking to Christ brings spiritual salvation" },
      ],
    },
    application: {
      thenAndNow: {
        originalMeaning: "Nicodemus, despite his religious knowledge and moral life, needed a complete spiritual rebirth. Religion and rule-following weren't enough - he needed to be transformed by God's Spirit from the inside out.",
        modernApplication: "We too can be 'good people' who attend church, know the Bible, and follow moral rules - yet still need the new birth. It's not about religious performance but heart transformation. And God's love extends to everyone, not just those who seem 'deserving.'",
      },
      reflectionQuestions: [
        "Have I experienced a genuine spiritual rebirth, or am I relying on religious activity?",
        "Do I truly believe God loves the WHOLE world - including people very different from me?",
        "Am I walking in the light, or are there areas of my life I'm hiding from God?",
        "How does knowing that God sent Jesus to SAVE, not condemn, change how I approach Him?",
        "Who in my life needs to hear that God loves them?",
      ],
      prayerPrompt: "Father, thank You for loving the world so much that You gave Your only Son. Help me to truly believe - not just mentally agree, but actively trust my whole life to Jesus. Search my heart and show me any areas still in darkness. Give me Your heart for the people around me who don't yet know Your love. In Jesus' name, Amen.",
      actionStep: "This week, share with one person (in word or action) that God loves them. It might be a friend who feels unlovable, a family member who's wandered from faith, or a stranger who needs kindness.",
    },
    connections: {
      relatedStories: [
        "Zacchaeus (Luke 19) - Another religious outsider who encountered Jesus personally",
        "The Woman at the Well (John 4) - Jesus offers 'living water' to an unlikely person",
        "Paul's Conversion (Acts 9) - A religious expert who needed radical transformation",
      ],
      prophecyLinks: [
        {
          oldTestament: "Isaiah 9:6-7",
          newTestament: "John 3:16",
          connection: "The promised Son who would rule forever is revealed as God's gift of love to the world",
        },
        {
          oldTestament: "Genesis 22:2 - Abraham's only son",
          newTestament: "John 3:16 - God's only Son",
          connection: "What God asked Abraham to do (but stopped), God Himself did - offering His own Son",
        },
      ],
      jesusConnection: "This passage is the heartbeat of the gospel: Jesus is the eternal Son of God, sent not as a condemning judge but as a loving Savior. His being 'lifted up' points to the cross, where He would die for the sins of the world. Through Him, anyone who believes receives eternal life.",
      bigPicture: "John 3 answers the fundamental human question: How can I be right with God? Not through religious effort (even Nicodemus couldn't earn it), but through God's initiative of love. This chapter connects Creation (God's love for the world He made), Fall (humans in darkness needing salvation), and Redemption (the Son given to save). It points forward to the cross and ultimately to new creation, where those born of the Spirit live forever with God.",
    },
    difficultQuestions: [
      {
        question: "What about people who never hear about Jesus?",
        honestAnswer: "Scripture doesn't give us a complete answer. We know God is just AND loving. Some passages suggest God judges based on the light people have received (Romans 2:12-16). What we know for certain: the gospel is for ALL people, and we're called to share it.",
        whatWeKnow: "God desires all to be saved (1 Tim 2:4). Jesus is the only way (John 14:6). God is perfectly just and merciful.",
        whatWeTrust: "God will do right (Genesis 18:25). His judgments are true and righteous. Our job is to share the good news, not to limit God's mercy.",
      },
      {
        question: "Why does God require belief? Isn't that unfair?",
        honestAnswer: "Belief isn't an arbitrary requirement - it's the nature of relationship. You can't have a relationship with someone you refuse to trust. God has made Himself known; faith is simply our response to His initiative.",
        whatWeKnow: "God takes the first step (He loved, He gave, He sent). Faith is a gift made possible by grace. God desires relationship, not forced compliance.",
        whatWeTrust: "God's requirements flow from His character of love. He has made the way accessible through Jesus. His Spirit enables genuine faith.",
      },
    ],
  },

  "GEN.1": {
    passage: "Genesis 1",
    context: {
      historical: "Written to Israel, likely during or after the Exodus, when they were surrounded by nations with competing creation stories. Egyptian and Babylonian myths featured chaotic battles between gods. Genesis presents one sovereign God creating peacefully by His word.",
      cultural: "Ancient Near Eastern cultures worshipped the sun, moon, and stars as gods. Genesis deliberately 'demotes' them - they're just lights that God made on Day 4. The creation account is subtly but powerfully counter-cultural.",
      literary: "Genesis 1 is highly structured and poetic, with parallel days (1-3 forming/4-6 filling) and repeated refrains ('And God said... and it was so... and it was good'). It reads like a hymn of praise to the Creator.",
      audience: "Israelites who had been slaves in Egypt, surrounded by polytheistic religions. They needed to know: Who is the true God? What is humanity's place? Why does the world exist?",
    },
    perspectives: {
      commonGround: [
        "God is the sole Creator of everything that exists",
        "Creation was intentional, not accidental",
        "Humans are uniquely made in God's image",
        "Creation was originally 'very good'",
        "God is sovereign over all He has made",
        "The Sabbath pattern is established by God",
      ],
      differentViews: [
        {
          view: "Young Earth Creation - six literal 24-hour days",
          traditions: ["Many Evangelicals", "Fundamentalists", "some Reformed"],
          reasoning: "The Hebrew word 'yom' with a number typically means a 24-hour day; straightforward reading of the text",
          heartBehind: "Deep commitment to biblical authority and taking Scripture at face value",
        },
        {
          view: "Old Earth Creation - 'days' as long ages",
          traditions: ["Many Catholics", "Orthodox", "some Evangelicals"],
          reasoning: "A 'day' to God is like a thousand years (2 Pet 3:8); allows harmony with scientific evidence",
          heartBehind: "Honoring both Scripture and God's revelation in nature",
        },
        {
          view: "Literary Framework - structured theology, not chronology",
          traditions: ["Many Reformed scholars", "some Catholics"],
          reasoning: "The parallel structure (days 1-3/4-6) suggests theological organization rather than strict sequence",
          heartBehind: "Reading Genesis in its ancient literary context",
        },
      ],
      unityNote: "Christians disagree on HOW and WHEN God created, but agree on WHO and WHY: the one true God intentionally created everything, including humans in His image, and called it good. Our unity is in the Creator, not in a particular scientific interpretation.",
    },
    deepDive: {
      keyWords: [
        {
          word: "Create",
          original: "בָּרָא (bara)",
          meaning: "To create something new; in the Bible, only God is the subject of 'bara'",
          significance: "This word emphasizes God's unique ability to bring into being something that didn't exist before.",
        },
        {
          word: "Image of God",
          original: "צֶלֶם אֱלֹהִים (tselem Elohim)",
          meaning: "Image, likeness, representation - like a statue representing a king",
          significance: "Humans uniquely represent God on earth - we have dignity, responsibility, and capacity for relationship with Him.",
        },
        {
          word: "Good",
          original: "טוֹב (tov)",
          meaning: "Good, beautiful, fitting, functioning as intended",
          significance: "Creation reflects God's character. Evil and suffering are intrusions, not part of God's original design.",
        },
      ],
      crossReferences: [
        { reference: "John 1:1-3", connection: "The Word (Jesus) was present at creation - 'through Him all things were made'" },
        { reference: "Colossians 1:16-17", connection: "All things created through Christ and for Christ; He holds all things together" },
        { reference: "Hebrews 11:3", connection: "By faith we understand that the universe was formed at God's command" },
        { reference: "Revelation 21:1", connection: "The story ends with new creation - God making all things new" },
      ],
      themes: [
        "God's Sovereignty",
        "The Power of God's Word",
        "Order from Chaos",
        "Human Dignity",
        "Sabbath Rest",
        "Goodness of Creation",
      ],
      symbols: [
        { symbol: "Light", meaning: "God's presence, truth, life - the first thing God creates before anything else" },
        { symbol: "Waters/Deep", meaning: "Ancient symbol of chaos; God's Spirit hovers over it, bringing order" },
        { symbol: "Breath/Spirit", meaning: "Hebrew 'ruach' - God's Spirit is present and active in creation" },
      ],
    },
    application: {
      thenAndNow: {
        originalMeaning: "Israel needed to know that their God - not the Egyptian or Canaanite gods - was the true Creator of everything. The sun wasn't a god; it was a lamp God made. They had worth because they bore God's image, not because Pharaoh said so.",
        modernApplication: "We live in a culture that often sees humans as accidents of nature or as consumers to be marketed to. Genesis says we have inherent dignity as God's image-bearers. Creation isn't just resources to exploit but a good gift to steward. And the Sabbath rhythm reminds us we're not machines - rest is part of God's design.",
      },
      reflectionQuestions: [
        "Do I live as if I'm an accident, or as someone made in God's image with purpose?",
        "How do I treat creation - as something to exploit or as a gift to steward?",
        "Do I practice Sabbath rest, or am I always producing?",
        "What does it mean that I'm made to represent God to the world around me?",
      ],
      prayerPrompt: "Creator God, thank You for making me in Your image. Help me see my own dignity and the dignity of every person I meet today. Forgive me for the ways I've failed to care for Your creation. Teach me the rhythm of work and rest that You designed. May my life reflect Your goodness. Amen.",
      actionStep: "Practice Sabbath this week - set aside time to rest, worship, and enjoy God's creation without producing or consuming. Simply be a creature enjoying the Creator.",
    },
    connections: {
      relatedStories: [
        "Psalm 104 - A poetic celebration of creation",
        "Job 38-41 - God reveals Himself through creation",
        "Revelation 21-22 - New creation, the story comes full circle",
      ],
      prophecyLinks: [
        {
          oldTestament: "Genesis 1:26 - Humanity made in God's image",
          newTestament: "Colossians 1:15 - Christ is the image of the invisible God",
          connection: "Jesus is the perfect image of God that humanity was always meant to reflect",
        },
      ],
      jesusConnection: "John 1 reveals that Jesus, the Word, was the agent of creation - 'through Him all things were made.' The same Word that spoke light into darkness spoke hope into our darkness. And just as God rested on the seventh day, Jesus offers us rest for our souls (Matthew 11:28).",
      bigPicture: "Genesis 1 is the opening scene of the Bible's story. A good God creates a good world and places humanity in it as His representatives. This sets up the tragedy of Genesis 3 (the Fall), the long journey of redemption, and the ultimate hope of Revelation 21-22 where God makes all things new. Everything in Scripture flows from and back to creation.",
    },
  },
};

// Helper to get study notes for a passage
export function getStudyNotes(bookId: string, chapter: number): StudyNotes | null {
  const key = `${bookId}.${chapter}`;
  return SAMPLE_NOTES[key] || null;
}
